### ISSUE TITLE
会加入批量导出一个公众号的文章吗

### ISSUE THREAD

**Issue by DavichiHug** [hi-andy/article-to-mobi#1]
会加入批量导出一个公众号的文章吗

**Comment by hi-andy** [comment]
如果后面有需求就会，不过有更好的想法。而一个公众号的所有文章，不一定都是精品。

发自我的 iPhone

在 2018年6月25日，18:26，Jack Thorne <notifications@github.com<mailto:notifications@github.com>> 写道：


会加入批量导出一个公众号的文章吗
