### ISSUE TITLE
既然你都自动生成mobi了，难道还想手动导入kindle吗？

### ISSUE THREAD

**Issue by suoba** [hi-andy/article-to-mobi#2]
既然你都自动生成mobi了，难道还想手动导入kindle吗？？？！！
建议将你的提交合并到KindleEar项目中去

**Comment by hi-andy** [comment]
导入不是频繁的操作，最主要想手动整理 kindle 里的内容。所以不需要自动导入，而是完全可控！感謝您的建议，謝謝！
